### PR TITLE
Resolves problems related to JSON parse error in UpdateDevce

### LINKED ISSUE #109: [BUG] Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
# Describe the bug
Error processing topics.

## To Reproduce

1. Just run plain vanilla zigbee2mqttassistant

**Expected behavior**
No such errors.

## Steps I took to try resolve the problem
Restart the add-on

## Screenshots
N/A

## Installation
 - Version of Zigbee2Mqtt: 1.6.0
 - Version of Zigbee2MqttAssistant: Lastest
 - Installation type (HASS.IO, Docker...): Hass.io
 - Docker version + CPU type (amd64, arm arm64...): N/A

## Pertinent logs
```
Starting Zigbee2MqttAssistant v0.3.88+Branch.master.Sha.a34fe059880e14ed9862286d6aa30d3853b87009...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another devices request already in progress.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 59
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 59
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
```

## Additional context
N/A

### LINKED ISSUE #203: [BUG] Error processing MQTT message on topic 'zigbee2mqtt/bridge/ota_update/update'
```
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/ota_update/update'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Z. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 493
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 400
```

### LINKED ISSUE #225: Z2M 'output' variable configuration cause errors
When zigbee2mqtt 'output' configuration variable is set to attribute or attribute_and_json, following errors are logged by the assistant as topic is not json data:

```
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/linkquality'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 2.
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/last_seen'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: T. Path '', line 1, position 10.
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ParseValue()
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/update_available'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Boolean. Path '', line 1, position 4.
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410

```

### PR DESCRIPTION
**Pull request by magpern**
Fixes #109 
Fixes #203 
Fixes #225 

For code review:
I added IsValidJSON to check the very basic needs of a JSON string. UpdateDevice called JObject.Parse(JsonString), which fails if JsonString is not a valid JSON.
I put a call to IsValidJson before this call. And if it returns false, UpdateDevice will return null.

Where UpdateDevice is used, it now checks for null before evaluating the rest of the if statement.

I also implemented some of the suggestions of code format that visual studio suggested

### CODE REVIEW

**Comment by carldebilly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yllibed/Zigbee2MqttAssistant/pullRequest?prid=5141497&bid=16889877)

File: Zigbee2MqttAssistant/Services/BridgeStateService.cs [hunk 1]
```diff
@@ -81,9 +82,43 @@ Bridge Update(Bridge state)
...
+			    (!strInput.StartsWith("[") || !strInput.EndsWith("]")))
+			{
+				//basic criteria for a JSON string/object not fulfilled
+				_logger.LogDebug($"Basic criteria for a JSON object is not met '{strInput}'");
+				return false;
+			}
+
+			try
+			{
+				JToken.Parse(strInput);
```
Comment (carldebilly) [inline Zigbee2MqttAssistant/Services/BridgeStateService.cs]: You're parsing the string twice. You should output the `JToken` as a `out` parameter in this case and use it by the caller.

**Comment by carldebilly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/yllibed/Zigbee2MqttAssistant/pullRequest?prid=5141497&bid=16889877)
